### ISSUE TITLE
Readme 위치 관련해서 의견 드립니다~!

### ISSUE THREAD

**Issue by hshine1226** [vos-team/vos-algorithm-study#3]
day_1 폴더에 문제 링크 관련해서 readme 만들어 주셨는데, 나중에 스터디 끝나고도 어떤 문제 풀었는지 한 번에 확인 가능하도록 각 폴더내에 만들지 말고 루트 경로에 만들어 두는게 어떨까요?

**Comment by jomujin** [comment]
네 좋은것 같습니다~ 오늘 준혁님께서 설명해주시는거 끝나고 pr후에 옮겨 놓겠습니다.
